package com.rentingbook.api.model.book.bookdetails;

public enum Genre {
    ArtsAndPhotography,
    BiographiesAndMemoirs,
    BusinessAndMoney,
    Calendars,
    BooksForChildren,
    ChristianBooksAndBibles,
    ComicsAndGraphicNovels,
    ComputersAndTechnology,
    Cookbooks, FoodAndWine,
    Crafts, HobbiesAndHome,
    EducationAndTeaching,
    EngineeringAndTransportation,
    Health, FitnessAndDieting,
    History,
    HumorAndEntertainment,
    Law,
    LiteratureAndFiction,
    MedicalBooks,
    MysteryAndThrillerAndSuspense,
    ParentingAndRelationships,
    PoliticsAndSocialSciences,
    Reference,
    ReligionAndSpirituality,
    Romance,
    ScienceAndMath,
    ScienceFictionAndFantasy,
    SelfHelp,
    SportsAndOutdoors,
    TeenAndYoungAdult,
    TestPreparation,
    Travel,
}
